[package]
name = "libchai"
version = "0.1.0"
authors = ["Songchen Tan <i@tansongchen.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
rand = "0.8.5"
time = "0.3.30"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4.31"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
serde_with = "3.4.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
