[package]
name = "libchai"
version = "0.1.0"
authors = ["Songchen Tan <i@tansongchen.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4.31"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
serde_with = "3.4.0"
csv = "1.3.0"
